import localFont from "next/font/local";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";
import NextTopLoader from "nextjs-toploader";
import { getUser } from "@/lib/apiCalls/user";
import { cookies } from "next/headers";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({ children }) {
  const cookieStore = cookies();

  // Retrieve a specific cookie by name
  const token = cookieStore.get("authtoken")?.value;
  let user;
  if (token) {
    const request = await getUser(token);
    if (request?.success) {
      user = request.user;
    }
  }

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <NextTopLoader
          color="#ff0000"
          height={4}
          showSpinner={false}
          delay={100} // Delay before loading bar appears
          transitionDuration={300} // Duration of the transition
        />
        <header className="border ">
          <Navbar user={user} />
        </header>
        <main className="py-32 md:py-24 ">{children}</main>
        <footer></footer>
      </body>
    </html>
  );
}
